name: Main workflow
on:
  workflow_run:
    workflows: 
      - upstream1
      - upstream2
    branches:
      - main
    types:
      - completed

jobs:
  wait_for_workflows:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1
        with:
          timeout: 1800000
          delay: 15000
      - run: echo "all workflows completed"

  build:
    runs-on: ubuntu-latest
    needs: wait_for_workflows
    steps:
      - run: echo "all workflows completed, now we can build"
