name: upstream2
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Doing some tests"
          sleep 120
          echo "Tests done after 120 seconds"
  