name: upstream1
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Doing some tests"
          sleep 60
          echo "Tests done after 60 seconds"
